const Map<String, String> indonesianLabels = {
  'person': 'Orang',
  'bicycle': 'Sepeda',
  'car': 'Mobil',
  'motorcycle': 'Sepeda Motor',
  'airplane': 'Pesawat',
  'bus': 'Bus',
  'train': 'Kereta',
  'truck': 'Truk',
  'boat': 'Perahu',
  'traffic light': 'Lampu Lalu Lintas',
  'fire hydrant': 'Hydrant Kebakaran',
  'stop sign': 'Rambu Stop',
  'parking meter': 'Parkir Meter',
  'bench': 'Bangku',
  'bird': 'Burung',
  'cat': 'Kucing',
  'dog': 'Anjing',
  'horse': 'Kuda',
  'sheep': 'Domba',
  'cow': 'Sapi',
  'elephant': 'Gajah',
  'bear': 'Beruang',
  'zebra': 'Zebra',
  'giraffe': 'Jerapah',
  'backpack': 'Tas Ransel',
  'umbrella': 'Payung',
  'handbag': 'Tas Tangan',
  'tie': 'Dasi',
  'suitcase': 'Koper',
  'frisbee': 'Frisbee',
  'skis': 'Ski',
  'snowboard': 'Papan Salju',
  'sports ball': 'Bola Olahraga',
  'kite': 'Layang-layang',
  'baseball bat': 'Pemukul Baseball',
  'baseball glove': 'Sarung Baseball',
  'skateboard': 'Papan Seluncur',
  'surfboard': 'Papan Selancar',
  'tennis racket': 'Raket Tenis',
  'bottle': 'Botol',
  'wine glass': 'Gelas Anggur',
  'cup': 'Cangkir',
  'fork': 'Garpu',
  'knife': 'Pisau',
  'spoon': 'Sendok',
  'bowl': 'Mangkuk',
  'banana': 'Pisang',
  'apple': 'Apel',
  'sandwich': 'Roti Lapis',
  'orange': 'Jeruk',
  'broccoli': 'Brokoli',
  'carrot': 'Wortel',
  'hot dog': 'Hot Dog',
  'pizza': 'Pizza',
  'donut': 'Donat',
  'cake': 'Kue',
  'chair': 'Kursi',
  'couch': 'Sofa',
  'potted plant': 'Tanaman Pot',
  'bed': 'Tempat Tidur',
  'dining table': 'Meja Makan',
  'toilet': 'Toilet',
  'tv': 'TV',
  'laptop': 'Laptop',
  'mouse': 'Mouse',
  'remote': 'Remote',
  'keyboard': 'Keyboard',
  'cell phone': 'Ponsel',
  'microwave': 'Microwave',
  'oven': 'Oven',
  'toaster': 'Pemanggang',
  'sink': 'Wastafel',
  'refrigerator': 'Kulkas',
  'book': 'Buku',
  'clock': 'Jam',
  'vase': 'Vas',
  'scissors': 'Gunting',
  'teddy bear': 'Boneka Beruang',
  'hair drier': 'Pengering Rambut',
  'toothbrush': 'Sikat Gigi',
};